version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Running RestAssured Tests...
      - mvn clean test
artifacts:
  files:
    - target/surefire-reports/*
